name: Dummy

on:
  pull_request:
    paths-ignore:
      - packages/backend/**
      - packages/misskey-js/**
      - .github/workflows/test-backend.yml
      - .node-version

permissions: {}

jobs:
  unit_backend:
    name: unit (backend)
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - run: 'true'

  e2e_backend_1:
    name: e2e (backend) (1)
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - run: 'true'

  e2e_backend_2:
    name: e2e (backend) (2)
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - run: 'true'

  e2e_backend_3:
    name: e2e (backend) (3)
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - run: 'true'

  e2e_backend_4:
    name: e2e (backend) (4)
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - run: 'true'
  
  merge_backend_e2e_coverage:
    name: merge_backend_e2e_coverage
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - run: 'true'

  test_federation:
    name: test (federation)
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - run: 'true'
