name: Dummy
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace:
        - backend
        - frontend
        - sw
        - misskey-js

    steps:
      - name: Dummy (${{ matrix.workspace }})
        run: echo dummy (${{ matrix.workspace }})

  typecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace:
        - backend
        - misskey-js

    steps:
      - name: Dummy (${{ matrix.workspace }})
        run: echo dummy (${{ matrix.workspace }})

  unit:
    runs-on: ubuntu-latest

    if: ${{ false }}

    steps:
      - name: Dummy
        run: echo dummy

  e2e:
    runs-on: ubuntu-latest

    if: ${{ false }}

    steps:
      - name: Dummy
        run: echo dummy

  test_misskey_js:
    runs-on: ubuntu-latest

    if: ${{ false }}

    steps:
      - name: Dummy
        run: echo dummy
