name: Dummy

on:
  pull_request:
    paths-ignore:
      - packages/backend/**
      - packages/misskey-js/**
      - .github/workflows/test-backend.yml
      - .node-version

permissions: {}

jobs:
  unit_backend:
    name: unit (backend)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    if: ${{ false }}
    steps:
      - run: 'true'

  e2e_backend:
    name: e2e (backend)
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - run: 'dummy'
