name: Pull Request Labeler

on:
  pull_request:
    branches-ignore:
      - 'l10n_develop'

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
    - name: Create labels
      uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
