name: Lint

on:
  push:
    branches:
      - master
      - develop
      - develop-mame
    paths:
      - packages/backend/**
      - packages/frontend/**
      - packages/sw/**
      - packages/misskey-js/**
      - packages/shared/eslint.config.js
      - .github/workflows/lint.yml
  pull_request:
    paths:
      - packages/backend/**
      - packages/frontend/**
      - packages/sw/**
      - packages/misskey-js/**
      - packages/shared/eslint.config.js
      - .github/workflows/lint.yml
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      eslint-cache-version: v1
    strategy:
      matrix:
        workspace:
        - backend
        - frontend
        - sw
        - misskey-js
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4.0.3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - run: git diff --exit-code pnpm-lock.yaml
    - name: Restore eslint cache
      uses: actions/cache@v4.0.2
      with:
        path: node_modules/.cache/eslint
        key: eslint-${{ env.eslint-cache-version }}-${{ hashFiles('/pnpm-lock.yaml') }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          eslint-${{ env.eslint-cache-version }}-${{ hashFiles('/pnpm-lock.yaml') }}-
    - run: pnpm --filter ${{ matrix.workspace }} run eslint --cache --cache-location node_modules/.cache/eslint --cache-strategy content

  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace:
        - backend
        - misskey-js
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4.0.3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - run: git diff --exit-code pnpm-lock.yaml
    - run: pnpm --filter misskey-js run build
      if: ${{ matrix.workspace == 'backend' }}
    - run: pnpm --filter ${{ matrix.workspace }} run typecheck
