name: Verify locales

on:
  push:
    branches:
      - master
      - develop
      - develop-mame
    paths:
      - locales/**
      - .github/workflows/locale.yml
      - .node-version
  pull_request:
    paths:
      - locales/**
      - .github/workflows/locale.yml
      - .node-version

permissions: {}

jobs:
  locale_verify:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - name: Enable Corepack
      run: corepack enable
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Check if lock file is not modified
      run: git diff --exit-code pnpm-lock.yaml
    - name: Verify locales
      run: cd locales && node verify.js
