name: Storybook

on:
  push:
    branches:
      - develop-mame
  pull_request:
    branches:
      - develop-mame

permissions: {}

jobs:
  build_storybook:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      NODE_OPTIONS: "--max_old_space_size=7168"

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      if: github.event_name == 'push'
      with:
        fetch-depth: 0
    - name: Checkout
      uses: actions/checkout@v4.1.1
      if: github.event_name == 'pull_request'
      with:
        fetch-depth: 0
        ref: "refs/pull/${{ github.event.number }}/merge"
    - name: Checkout actual HEAD
      if: github.event_name == 'pull_request'
      id: rev
      run: |
        echo "base=$(git rev-list --parents -n1 HEAD | cut -d" " -f2)" >> $GITHUB_OUTPUT
        git checkout $(git rev-list --parents -n1 HEAD | cut -d" " -f3)
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - name: Enable Corepack
      run: corepack enable
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Check if lock file is not modified
      run: git diff --exit-code pnpm-lock.yaml
    - name: Build misskey-js
      run: pnpm --filter misskey-js run build
    - name: Build Storybook
      run: pnpm --filter frontend run build-storybook
    - name: Publish to Chromatic
      uses: chromaui/action@v11.10.4
      with:
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        onlyChanged: true
        exitOnceUploaded: true
        workingDir: packages/frontend
        storybookBaseDir: packages/frontend
        storybookBuildDir: storybook-static
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: storybook
        path: packages/frontend/storybook-static
