name: Test

on:
  push:
    branches: [ develop, develop-mame ]
    paths:
      - packages/misskey-js/**
      - .github/workflows/test-misskey-js.yml
      - .node-version

  pull_request:
    branches: [ develop, develop-mame ]
    paths:
      - packages/misskey-js/**
      - .github/workflows/test-misskey-js.yml
      - .node-version

permissions: {}

jobs:
  test:
    name: test (misskey-js)

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check if lock file is not modified
        run: git diff --exit-code pnpm-lock.yaml
      - name: Build misskey-js
        run: pnpm --filter misskey-js run build
      - name: Test
        run: pnpm --filter misskey-js run test
        env:
          CI: true
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/misskey-js/coverage/coverage-final.json
