name: Test

on:
  push:
    branches:
      - master
      - develop
      - develop-mame
    paths:
      - packages/frontend/**
      # for permissions
      - packages/misskey-js/**
      # for e2e
      - packages/backend/**
      - .github/workflows/test-frontend.yml
      - .node-version
  pull_request:
    paths:
      - packages/frontend/**
      # for permissions
      - packages/misskey-js/**
      # for e2e
      - packages/backend/**
      - .github/workflows/test-frontend.yml
      - .node-version

permissions: {}

jobs:
  vitest:
    name: vitest (frontend)

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - name: Enable Corepack
      run: corepack enable
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Check if lock file is not modified
      run: git diff --exit-code pnpm-lock.yaml
    - name: Copy config file
      run: cp .github/misskey/test.yml .config
    - name: Build
      run: pnpm --filter misskey-js run build
    - name: Test
      run: pnpm --filter frontend run test-and-coverage
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./packages/frontend/coverage/coverage-final.json
        flags: frontend_vitest

  e2e:
    name: e2e (frontend)

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    services:
      postgres:
        image: postgres:15
        ports:
          - 54312:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:7
        ports:
          - 56312:6379

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - name: Enable Corepack
      run: corepack enable
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Check if lock file is not modified
      run: git diff --exit-code pnpm-lock.yaml
    - name: Copy config file
      run: cp .github/misskey/test.yml .config
    - name: Build
      run: pnpm run build
    # https://github.com/cypress-io/cypress/issues/4351#issuecomment-559489091
    - name: ALSA Env
      run: echo -e 'pcm.!default {\n type hw\n card 0\n}\n\nctl.!default {\n type hw\n card 0\n}' > ~/.asoundrc
    # XXX: This tries reinstalling Cypress if the binary is not cached
    # Remove this when the cache issue is fixed
    - name: Install Cypress
      run: pnpm exec cypress install
    - name: Run Cypress
      uses: cypress-io/github-action@v6
      timeout-minutes: 15
      with:
        install: false
        start: pnpm run start:test
        wait-on: 'http://localhost:61812'
        headed: true
        browser: chrome
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: chrome-cypress-screenshots
        path: cypress/screenshots
    - name: Upload videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: chrome-cypress-videos
        path: cypress/videos
