name: Test

on:
  push:
    branches:
      - master
      - develop
      - develop-mame
    paths:
      - packages/frontend/**
      # for permissions
      - packages/misskey-js/**
      # for e2e
      - packages/backend/**
      - .github/workflows/test-frontend.yml
  pull_request:
    paths:
      - packages/frontend/**
      # for permissions
      - packages/misskey-js/**
      # for e2e
      - packages/backend/**
      - .github/workflows/test-frontend.yml
jobs:
  vitest:
    name: vitest (frontend)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4.0.3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - name: Check pnpm-lock.yaml
      run: git diff --exit-code pnpm-lock.yaml
    - name: Copy Configure
      run: cp .github/misskey/test.yml .config
    - name: Build
      run: pnpm build
    - name: Test
      run: pnpm --filter frontend test-and-coverage
    - name: Upload Coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./packages/frontend/coverage/coverage-final.json

  e2e:
    name: e2e (frontend)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    services:
      postgres:
        image: postgres:15
        ports:
          - 54312:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:7
        ports:
          - 56312:6379

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true
    # https://github.com/cypress-io/cypress-docker-images/issues/150
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4.0.3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - name: Check pnpm-lock.yaml
      run: git diff --exit-code pnpm-lock.yaml
    - name: Copy Configure
      run: cp .github/misskey/test.yml .config
    - name: Build
      run: pnpm build
    # https://github.com/cypress-io/cypress/issues/4351#issuecomment-559489091
    - name: ALSA Env
      run: echo -e 'pcm.!default {\n type hw\n card 0\n}\n\nctl.!default {\n type hw\n card 0\n}' > ~/.asoundrc
    # XXX: This tries reinstalling Cypress if the binary is not cached
    # Remove this when the cache issue is fixed
    - name: Cypress install
      run: pnpm exec cypress install
    - name: Cypress run
      uses: cypress-io/github-action@v6
      timeout-minutes: 15
      with:
        install: false
        start: pnpm start:test
        wait-on: 'http://localhost:61812'
        headed: true
        browser: chrome
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: chrome-cypress-screenshots
        path: cypress/screenshots
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: chrome-cypress-videos
        path: cypress/videos
