name: Test

on:
  push:
    branches:
      - master
      - develop
      - develop-mame
    paths:
      - packages/backend/**
      # for permissions
      - packages/misskey-js/**
      - .github/workflows/test-backend.yml
      - .node-version
  pull_request:
    paths:
      - packages/backend/**
      # for permissions
      - packages/misskey-js/**
      - .github/workflows/test-backend.yml
      - .node-version

permissions: {}

jobs:
  unit:
    name: unit (backend)

    runs-on: ubuntu-latest

    permissions:
      contents: read

    services:
      postgres:
        image: postgres:15
        ports:
          - 54312:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:7
        ports:
          - 56312:6379

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@36c6454b5a2348e7794ba2d82a21506605921e3d
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - name: Enable Corepack
      run: corepack enable
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Check if lock file is not modified
      run: git diff --exit-code pnpm-lock.yaml
    - name: Copy config file
      run: cp .github/misskey/test.yml .config
    - name: Pre-build and Build misskey-js
      run: pnpm run build-pre && pnpm --filter misskey-js run build
    - name: Get jest cache path
      id: get-jest-cache-path
      run: echo "path=$(pnpm --silent --filter backend run jest --showConfig | jq -r '.configs[0].cacheDirectory')" >> $GITHUB_OUTPUT
    - name: Restore jest cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.get-jest-cache-path.outputs.path }}
        key: jest-backend-unit-v1-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: jest-backend-unit-v1-${{ hashFiles('**/pnpm-lock.yaml') }}-
    - name: Test
      run: pnpm --filter backend run test-and-coverage
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./packages/backend/coverage/coverage-final.json

  e2e:
    name: e2e (backend)

    runs-on: ubuntu-latest

    permissions:
      contents: read

    services:
      postgres:
        image: postgres:15
        ports:
          - 54312:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:7
        ports:
          - 56312:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check if lock file is not modified
        run: git diff --exit-code pnpm-lock.yaml
      - name: Copy config file
        run: cp .github/misskey/test.yml .config
      - name: Pre-build and Build misskey-js
        run: pnpm run build-pre && pnpm --filter misskey-js run build
      - name: Get jest cache path
        id: get-jest-cache-path
        run: echo "path=$(pnpm --silent --filter backend run jest --showConfig | jq -r '.configs[0].cacheDirectory')" >> $GITHUB_OUTPUT
      - name: Restore jest cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-jest-cache-path.outputs.path }}
          key: jest-backend-e2e-v1-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: jest-backend-e2e-v1-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Test
        run: pnpm --filter backend run test-and-coverage:e2e
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/backend/coverage/coverage-final.json
