# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [ develop, develop-mame ]
    paths:
      - packages/misskey-js/**
      - .github/workflows/test-misskey-js.yml
  pull_request:
    branches: [ develop, develop-mame ]
    paths:
      - packages/misskey-js/**
      - .github/workflows/test-misskey-js.yml
jobs:
  test:
    name: test (misskey-js)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - run: corepack enable

      - uses: actions/setup-node@v4.0.3
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Check pnpm-lock.yaml
        run: git diff --exit-code pnpm-lock.yaml

      - name: Build
        run: pnpm --filter misskey-js build

      - name: Test
        run: pnpm --filter misskey-js test
        env:
          CI: true

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/misskey-js/coverage/coverage-final.json
